### ISSUE TITLE
vertex color won't be correctly rendered on the subviewer.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#76] opened 2024-01-25 20:46 UTC
Hi koide3,
I found an issue with the point cloud in the sub-viewer that can't be correctly rendered with its vertex color. The problem only shows in cpp implementation, but the python one works correctly (wired). The cloud vertex color is rendered in the main viewer correctly. The geometries of both clouds in the main and sub-viewer are rendered correctly.

Here are several things I tried.
1. swap the rgba cloud for the main and sub-viewer, (no color in sub)
2. swap the shader_setting for the main and sub-viewer. (no color in sub)
3. only render the cloud in the subviewer. (no color in sub)
4. let the main and sub-viewer render the same cloud and shader (no color in sub)
5. render other objects e.g. shpere in the sub-viewer and check different shader settings (this works).

Could you share me some insight about how to solve this?

Thanks

![Screenshot from 2024-01-25 15-45-59](https://github.com/koide3/iridescence/assets/33109925/5cad0ce5-8b52-4281-99d8-04ff8990015c)

**Comment by koide3** [comment] 2024-01-27 09:26
Hmmm, I was unable to reproduce the bug with the following code, and I guess the bug may occur depending on the order or timing of  PointCloudBuffer creation or registration. It would be so helpful to dig into the issue if you could provide a minimum example code to reproduce the bug.

```cpp
#include <glk/pointcloud_buffer.hpp>
#include <guik/viewer/light_viewer.hpp>

int main(int argc, char** argv) {
  auto viewer = guik::viewer();

  const int num_points = 2048;
  std::vector<Eigen::Vector3f> points(num_points);
  std::vector<Eigen::Vector4f> colors(num_points);
  for (int i = 0; i < num_points; i++) {
    points[i] = Eigen::Vector3f::Random();
    colors[i] << (points[i].array() + 1.0) * 0.5, 1.0;
  }

  auto cloud_buffer = std::make_shared<glk::PointCloudBuffer>(points);
  cloud_buffer->add_color(colors);

  // viewer->update_drawable("points", cloud_buffer, guik::VertexColor());

  auto sub_viewer = viewer->sub_viewer("sub");
  sub_viewer->update_drawable("points", cloud_buffer, guik::VertexColor());

  viewer->spin();

  return 0;
}
```

**Comment by Seekerzero** [comment] 2024-01-28 01:25
Here is my code example. The code you share with me above also works on my side, I think the difference between our codes is that I use pcl to read the pointcloud file and use the glk::create_colored_point_cloud_buffer() because I want to load the colored pointcloud in once. And the colored pointcloud I load is the redwood indoor [laser scan data](https://drive.google.com/file/d/0B-ePgl6HF260a3MtSWJIY1pBSG8/view?resourcekey=0-nksfQmjgI7t4WEUmLaUQgA)  (the original one is a ply file, and I converted it into a pcd file). 
`
// #include <imgui.h>
#include <pcl/io/pcd_io.h>
#include <pcl/io/ply_io.h>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/console/print.h>
#include <portable-file-dialogs.h>
#include <glk/pointcloud_buffer.hpp>
#include <glk/pointcloud_buffer_pcl.hpp>
#include <glk/primitives/primitives.hpp>
#include <glk/splatting.hpp>
#include <guik/viewer/light_viewer.hpp>

#include <portable-file-dialogs.h>


int main(int argc, char** argv) {
  //set the background
  auto viewer = guik::LightViewer::instance();
  viewer->set_clear_color({0.8f, 0.8f, 0.8f, 1.0f});
  auto topdownViewer = viewer->sub_viewer("TopdownView");
  topdownViewer->set_clear_color({0.8f, 0.8f, 0.8f, 1.0f});
  topdownViewer->enable_info_buffer();
  topdownViewer->use_topdown_camera_control(40.0,0.0);
  
  const int num_points = 2048;
  std::vector<Eigen::Vector3f> points(num_points);
  std::vector<Eigen::Vector4f> colors(num_points);
  for (int i = 0; i < num_points; i++) {
    points[i] = Eigen::Vector3f::Random();
    colors[i] << (points[i].array() + 1.0) * 0.5, 1.0;
  }

  // Register a callback for UI rendering
  static char text[10] = "";
  ImGuiInputTextFlags flags = (
        ImGuiInputTextFlags_CharsUppercase
        | ImGuiInputTextFlags_CharsNoBlank
    );
  float pointScale = 2.0f;
  auto rawCloud = pcl::PointCloud<pcl::PointXYZRGBA>::Ptr(new pcl::PointCloud<pcl::PointXYZRGBA>);

  viewer->register_ui_callback("ui", [&]() {
    ImGui::Begin("UI",0,ImGuiWindowFlags_AlwaysAutoResize);
    if(ImGui::Button("Load PointCloud")){
      std::vector<std::string> results = pfd::open_file("choose a PCD file").result();
      if(!results.empty()) {
        if(pcl::io::loadPCDFile<pcl::PointXYZRGBA> (results[0], *rawCloud) == -1) //* load the file
        {
          PCL_ERROR ("Couldn't read the pcdfile \n");
        }
      }
      auto cloud_buffer = glk::create_colored_point_cloud_buffer(*rawCloud);
      // cloud_buffer->add_color(colors);
      // viewer->update_drawable("points", cloud_buffer, guik::VertexColor());
      viewer->update_drawable("points", cloud_buffer, guik::VertexColor());
      topdownViewer->update_drawable("points", cloud_buffer, guik::VertexColor());
    }
    ImGui::Separator();
    if (ImGui::Button("Close")) {
      viewer->close();
    }
    ImGui::End();
  });
  
  while (viewer->spin_once()) {
  }

  return 0;
}
`

**Comment by koide3** [comment] 2024-02-04 08:47
I found that the scan data has colors with zero alpha values, and setting alpha=1 for point colors resolved the issue. I'm still wondering why this only happens on the sub viewer and trying to fix it.

**Comment by koide3** [comment] 2024-02-04 09:38
I seems this bug is caused by rendering points with alpha=0 that makes pixels rendered with `ImGui::Image` transparent. I fixed the issue using OpenGL's Texture swizzles settings. The [PR](https://github.com/koide3/iridescence/pull/79) will be merged after checking that it does not cause side effects.

**Comment by Seekerzero** [comment] 2024-02-05 21:25
Thanks for the update! I just confirmed that it was also fixed on my side.
I think we can close this issue.

**Closed** 2024-02-06 09:08 UTC
